[workspace]
members = [
    "callisto",
]

resolver="2"

[workspace.dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.7", features = ["derive"]}
polars = { version = "0.40.0", features = ["sql"]}
serde = "1.0.203"
serde_json = "1.0.117"
