[package]
name = "callisto"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
polars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
